import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = dirname(fileURLToPath(import.meta.url));
const migrationsDir = join(root, '..', 'drizzle');
const outFile = join(root, '..', 'src', 'db', 'migrations-bundle.ts');

const files = readdirSync(migrationsDir)
  .filter((f) => f.endsWith('.sql'))
  .sort();

const entries = files.map((f) => {
  const sql = readFileSync(join(migrationsDir, f), 'utf8');
  const name = f.replace(/\.sql$/, '');
  return { name, sql };
});

const escapeBacktickString = (s: string) =>
  s.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${');

const body = `// Generated by scripts/bundle-migrations.ts — do not edit by hand.
export const MIGRATIONS: { name: string; sql: string }[] = [
${entries.map((e) => `  { name: '${e.name}', sql: \`${escapeBacktickString(e.sql)}\` },`).join('\n')}
];
`;

writeFileSync(outFile, body);
console.log(`bundled ${entries.length} migration(s) → ${outFile}`);
